namespace H3M.Models;

public enum MetaType
{
    GenericImpassableTerrain,
    GenericImpassableTerrainAbSoD,
    GenericVisitable,
    GenericVisitableAbSoD,
    Artifact,
    AbandonedMineAbSoD,
    Dwelling,
    Event,
    Garrison,
    GarrisonAbSoD,
    GenericBoat,
    GenericPassableTerrainSoD,
    GenericPassableTerrain,
    PandorasBox,
    Grail,
    Hero,
    Lighthouse,
    Monster,
    OceanBottle,
    Prison,
    QuestGuard,
    RandomDwellingAbSoD,
    RandomDwellingPresetLevelAbSoD,
    RandomDwellingPresetAlignmentAbSoD,
    RandomHero,
    PlaceholderHero,
    Resource,
    ResourceGenerator,
    Scholar,
    SeersHut,
    Shipyard,
    Shrine,
    Sign,
    SpellScroll,
    SubterraneanGate,
    Town,
    RandomTown,
    WitchHut,
    GenericTreasure,
    
    Unknown = -1
}
